### ISSUE TITLE
[Bug]: Markdown file created but no annotation extracted from pdf

### ISSUE THREAD

**Issue by andreatitolo** [chrisgrieser/pdf-annotation-extractor-alfred#12]
### Bug Description

When running the shortcut on a selected file in Finder, the .md file is correctly created with the YAML and the Author/Title, but the annotations are not attached to the file. Same happens if I use the 'anno' command.

Debugging log file: [alfredDebug.txt](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/files/10475372/alfredDebug.txt)

Edit: I just ran the workflow inside PDF Expert, and I get the warning "File is not a PDF", don't know if that helps.

### To Reproduce

1. Select a pdf file in the Finder
2. Run the shortcut with the hotkey
3. The .md file is created but no annotation are present

### Debugging Log

```Text
See attached file above
```

### Workflow Configuration

<img width="517" alt="image" src="https://user-images.githubusercontent.com/61151275/213937321-ce71c5bf-0193-43c3-ba9b-ca730e0bd2d2.png">

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/releases/latest) of this workflow.
- [X] If the extracted text is all jumbled up (special characters, spaces missing, etc.) then the issue is not with this workflow, but the underlying extraction engine, pdfannots2json. Upgrade it to the latest version with `brew upgrade pdfannots2json` and try again. If the issue persists, [file a bug report at pdfannots2json.](https://github.com/mgmeyers/pdfannots2json/issues)

**Comment by chrisgrieser** [comment]
should be fixed in latest release
