### ISSUE TITLE
[Bug]: Not a .pdf file

### ISSUE THREAD

**Issue by andreatitolo** [chrisgrieser/pdf-annotation-extractor-alfred#15]
### Bug Description

First of all, thank you for this workflow! :)

It seems the workflow can not extract annotations anymore for me. Both pdfannots2json and pdfannots methods fail with the error "Not a .pdf file". 
However, when run independently of this workflow, I am able to get the annotations from a pdf using both pdfannots2json and pdfannots.

Judging from the debug log (see below) the workflow is not able to get the current_file variable?
Thanks for your help :)

### To Reproduce

1. Select a PDF file in finder
2. Use the hotkey
3. Get the error "not a pdf file"

### Debugging Log

```Text
[10:38:34.625] PDF Annotation Extractor[Hotkey] Processing complete
[10:38:34.634] PDF Annotation Extractor[Hotkey] Passing output '' to Run Script
[10:38:35.080] ERROR: PDF Annotation Extractor[Run Script] ./scripts/get-pdf-path.applescript:1348:1360: execution error: Variable current_file is not defined. (-2753)
```

### Workflow Configuration

![workflow](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/assets/61151275/e3869051-e157-4d1e-8fbf-7af051e6733f)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/releases/latest) of this workflow.
- [X] If the extracted text is all jumbled up (special characters, spaces missing, etc.) then the issue is not with this workflow, but the underlying extraction engine, pdfannots2json. Upgrade it to the latest version with `brew upgrade pdfannots2json` and try again. If the issue persists, [file a bug report at pdfannots2json.](https://github.com/mgmeyers/pdfannots2json/issues)

**Comment by chrisgrieser** [comment]
ah yes, I haven't properly updates this workflow in a while. should be fixed with the latest release
