### ISSUE TITLE
[Bug]: cannot create note

### ISSUE THREAD

**Issue by EroyalBoy** [chrisgrieser/pdf-annotation-extractor-alfred#16]
### Bug Description

 When triggered keywords or hotkeys , cannot create a notes into goal file.(obsidian show cannot find notes in literaurenotes.

### Relevant Screenshot

![CleanShot 2023-08-02 at 16 53 10](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/assets/36374478/c3c5bb4c-2b82-4ffa-be2d-95b60fabea4e)

### Debugging Log

```Text
[16:47:21.368] Logging Started...
[16:47:39.541] PDF Annotation Extractor[File Filter] Processing complete
[16:47:39.542] PDF Annotation Extractor[File Filter] Passing output '/Users/zephyrfang/Zotero/storage/JKQDT4CA/dunlosky2013_improving_students’_learning_with_effective_learning_techniques.pdf' to Run Script
[16:47:39.951] PDF Annotation Extractor[Run Script] Processing complete
[16:47:39.952] PDF Annotation Extractor[Run Script] Passing output '' to Post Notification
```

### Workflow Configuration

![CleanShot 2023-08-02 at 16 46 59](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/assets/36374478/15774f3b-2150-4662-958c-8dc6d3662fae)
![CleanShot 2023-08-02 at 16 51 13](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/assets/36374478/8830f891-7aa3-4f5b-a874-624223b938e4)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/releases/latest) of this workflow.
- [X] If the extracted text is all jumbled up (special characters, spaces missing, etc.) then the issue is not with this workflow, but the underlying extraction engine, pdfannots2json. Upgrade it to the latest version with `brew upgrade pdfannots2json` and try again. If the issue persists, [file a bug report at pdfannots2json.](https://github.com/mgmeyers/pdfannots2json/issues)

**Comment by chrisgrieser** [comment]
PR #17 has fixed the issue. Works again in the latest release: https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/releases/download/8.8.0/pdf-annotation-extractor-alfred.alfredworkflow
