### ISSUE TITLE
Can I disable BibTex Library Path?

### ISSUE THREAD

**Issue by hyjwonder** [chrisgrieser/pdf-annotation-extractor-alfred#19]
### Bug Description

BibTex Library Path is a required field. However, I have lots of private PDFs. How can I work without a .bib file?
(Actually, I don't know what a .bib file is.)

### Debugging Log

```Text
N/A
```

### Workflow Configuration

Default

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/releases/latest) of this workflow.
- [X] If the extracted text is all jumbled up (special characters, spaces missing, etc.) then the issue is not with this workflow, but the underlying extraction engine, pdfannots2json. Upgrade it to the latest version with `brew upgrade pdfannots2json` and try again. If the issue persists, [file a bug report at pdfannots2json.](https://github.com/mgmeyers/pdfannots2json/issues)

**Comment by chrisgrieser** [comment]
Yeah, the way the workflow currently works requires a bib file. The idea is that this workflow not just extracts annotations, but also inserts page numbers for academic citations.

Adding support for extraction without a bib-file would be an entirely new feature, for which I personally do not have any use. If there is more interest in it, I'd consider adding that though

**Comment by hyjwonder** [comment]
Got your point. I tried making a Fake .bib file (without any content) but the it does not work. Anyway, I hope this could be an option to make it more usable for non-academic purposes.

**Comment by chrisgrieser** [comment]
Okay, I actually had a use case for that and have therefore implemented the feature this afternoon. The BibTeX file is now optional.
https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/releases/download/9.0.0/pdf-annotation-extractor-alfred.alfredworkflow
