### ISSUE TITLE
Feature Request: An alternative extraction engine

### ISSUE THREAD

**Issue by sirlaughalot90** [chrisgrieser/pdf-annotation-extractor-alfred#23]
### Feature Requested

Unfortunately, mgmeyer's pdfannots2json has some major flaws as it wrongly interprets certain letter combinations (e.g. fl or Th). I have already filed a bug report with him a couple of weeks ago but got no response (see here: https://github.com/mgmeyers/pdfannots2json/issues/22). If possible, I would therefore propose the possibility of adding a third engine to mitigate the issue – preferably one that is maintained by more than one person, if such exists.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Well, if you are aware of any extraction engine other than `pdfannots2json` and `pdfannots`, I'll gladly add support for it. Problem being that I simply do not know any other good CLIs that export PDF annotations.
