### ISSUE TITLE
[Bug]: Meta Data Extraction not working anymore

### ISSUE THREAD

**Issue by sirlaughalot90** [chrisgrieser/pdf-annotation-extractor-alfred#25]
### Bug Description

Only the highlights will get extracted, not the meta data.

### To Reproduce

1. Open the PDF in PDF Expert
2. Run the keyboard shortcut

### Debugging Log

```Text
[15:10:22.320] Logging Started...
[15:10:29.710] PDF Annotation Extractor[Hotkey] Processing complete
[15:10:29.718] PDF Annotation Extractor[Hotkey] Passing output '' to Run Script
[15:10:31.147] PDF Annotation Extractor[Run Script] Processing complete
[15:10:31.153] PDF Annotation Extractor[Run Script] Passing output '' to Post Notification
```

### Workflow Configuration

![CleanShot 2024-02-19 at 15 13 17@2x](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/assets/20352339/8dcfd0e4-4bd2-459b-91ec-1536835e2a7b)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/releases/latest) of this workflow.
- [X] If the extracted text is all jumbled up (special characters, spaces missing, etc.) then the issue is not with this workflow, but the underlying extraction engine, pdfannots2json. Upgrade it to the latest version with `brew upgrade pdfannots2json` and try again. If the issue persists, [file a bug report at pdfannots2json.](https://github.com/mgmeyers/pdfannots2json/issues)

**Comment by chrisgrieser** [comment]
Still works fine on my end. Also, there hasn't been a new release the last couple of weeks, so nothing on this workflow's side could have really changed.

So I suspect the issue lies rather with the particular paper. Maybe the bibtex data for the entry is somehow invalid?

I'd try different PDFs, and compare the working PDFs with the non-working ones.

**Comment by sirlaughalot90** [comment]
Thank you. I'd try a couple more this evening. However, I've already tried 5ish papers – all with the same result. Could – in theory – a recent Zotero update break the workflow?

**Comment by chrisgrieser** [comment]
Do filename & citekey in the bibtex file match? A missing match of those could be the issue. A Zotero update might have changed how citekeys are generated

**Comment by sirlaughalot90** [comment]
Another weird thing happening: It does not honour the output path (which should be a folder in Obsidian and is configured as such) but puts it into the PDF's folder. I have no idea why. The Bibtex flie is alright as the Pandoc Reference List plugin which uses the same file resolves everything correctly.

**Comment by chrisgrieser** [comment]
That happens when there is a mismatch between pdf filename and bibtex citekey. 

Please post the filename and the bibtex entry here?

**Comment by sirlaughalot90** [comment]
Oh boy... I am stupid. I've been on vacation for the past 2 weeks and in the meantime I unlearned the workflow, apparently. I forgot to rename the file with the citekey. Everything works as expected – I am sorry! 🤦‍♂️

However, there is another bug (?) regarding the true page number – would you like me to open a new thread for this? Executive summary: when entering the true first page number it is off by 1, e.g. the most recent paper I read starts with a title page which is followed by the first text page which is numbered 1. When I enter -1 in the dialoge I still get page 2 for highlights on page 1. This behaviour is consistent for every paper I had to enter a page number, so either I misunderstand how the feature works or there is an off-by-one error.

**Comment by chrisgrieser** [comment]
Hmm, open a new issue for that and share the pdf and the bibtex entry there so I can have a look?
