### ISSUE TITLE
[Bug]: Possible Off-by-One Error regarding true page number

### ISSUE THREAD

**Issue by sirlaughalot90** [chrisgrieser/pdf-annotation-extractor-alfred#26]
### Bug Description

When entering the true first page number it is off by 1, e.g. the most recent paper I read starts with a title page which is followed by the first text page which is numbered 1. When I enter -1 in the dialoge I still get page 2 for highlights on page 1. This behaviour is consistent for every paper I had to enter a page number, so either I misunderstand how the feature works or there is an off-by-one error.

### Relevant Screenshot

[hooghe_2020_PostfunctionalistTheoryMultilevel.pdf](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/files/14341801/hooghe_2020_PostfunctionalistTheoryMultilevel.pdf)

Bibtex entry:

@article{hooghe2009PostfunctionalistTheoryMultilevel,
  title = {A Postfunctionalist Theory of Multilevel Governance},
  author = {Hooghe, Liesbet and Marks, Gary},
  date = {2009},
  journaltitle = {The British Journal of Politics and International Relations},
  shortjournal = {The British Journal of Politics and International Relations},
  volume = {22},
  number = {4},
  pages = {1--23},
  issn = {1369-1481, 1467-856X},
  doi = {10.1177/1369148120935303},
  url = {http://journals.sagepub.com/doi/10.1177/1369148120935303},
  urldate = {2022-11-29},
  abstract = {Multilevel governance describes the diffusion of authority away from the central state. In this contribution, we recount how an archaic term, governance, became part of the vocabulary of political science. We then outline three building blocks of a postfunctionalist theory of multilevel governance. The first is that multilevel governance is cooperation to provide collective goods at diverse scales. The second is that the form governance takes depends on the sociality of the participants. The third is that conflict over community enables or impedes multilevel governance.},
  langid = {english},
  keywords = {read},
  file = {/Users/jan/Zotero/storage/EJTC87K5/Hooghe and Marks - 2020 - A postfunctionalist theory of multilevel governanc.pdf}
}

### To Reproduce

1. Press shortcut to extract
2. Enter -1 as the pdf starts with a title page, followed by page 1.

### Debugging Log

```Text
[10:03:19.688] PDF Annotation Extractor[Hotkey] Processing complete
[10:03:19.700] PDF Annotation Extractor[Hotkey] Passing output '' to Run Script
[10:03:23.697] STDERR: PDF Annotation Extractor[Run Script] rmdir: /Users/jan/Obsidian/0 Seedbox/attachments: Directory not empty
[10:03:23.705] PDF Annotation Extractor[Run Script] Processing complete
[10:03:23.706] PDF Annotation Extractor[Run Script] Passing output '' to Post Notification
```

### Workflow Configuration

![CleanShot 2024-02-19 at 15 13 17@2x](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/assets/20352339/1b668d4c-a09c-4f8a-94f4-bdb97feeb9d1)

### Checklist

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/releases/latest) of this workflow.
- [X] If the extracted text is all jumbled up (special characters, spaces missing, etc.) then the issue is not with this workflow, but the underlying extraction engine, pdfannots2json. Upgrade it to the latest version with `brew upgrade pdfannots2json` and try again. If the issue persists, [file a bug report at pdfannots2json.](https://github.com/mgmeyers/pdfannots2json/issues)

**Comment by chrisgrieser** [comment]
Ah yes. The prompt to enter the first page number only appears if the entry is missing that information. That is intentional, since otherwise automatic page number identification is not possible, and there is little I can do about it on my end, I'm afraid, since there is no way for the workflow to detect if there is a title page or not.

What I do is either to remove the title page (all the relevant information is in my reference manager already anyway), or move that title page to the end of the document.
