### ISSUE TITLE
rectangular selections?

### ISSUE THREAD

**Issue by rhaynes74** [chrisgrieser/pdf-annotation-extractor-alfred#3]
Hi folks, is it possible to select rectangular (image) selections and have them exported to markdown (links to graphics files for example)?

**Comment by chrisgrieser** [comment]
no folks, just me :)

I'd like to have such a feature as well, however such a feature is dependent on improvements to [pdfannots](https://github.com/0xabu/pdfannots) enabling it. You can make a feature request there!

Best I could do is implement the [annotation code for images](https://github.com/chrisgrieser/pdf-annotation-extractor-alfred#annotation-codes), which unfortunately only works with Obsidian as output.

**Comment by rhaynes74** [comment]
Thanks for the quick response.   I will explore the annotation code for images idea and file a feature request with pdfannots.

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
