### ISSUE TITLE
Feature Request: Add keywords input to trigger workflow as an alternative of shortcuts trigger.

### ISSUE THREAD

**Issue by secondbrain-note** [chrisgrieser/pdf-annotation-extractor-alfred#4]
**Feature Requested**
Add keywords input to trigger workflow as an alternative of shortcuts trigger.
Because sometimes it is more convenient to remember the keywords than the shortcuts and sometimes shortcuts may be used in other apps.
**Relevant Screenshots**
![image](https://user-images.githubusercontent.com/69676588/150758792-6dbef1fd-7228-498a-92f7-aa5cb5947431.png)
Notice the red box. That's what I mean.

**Checklist**
- [x] The feature would be useful to more users than just me.

Thanks.

**Comment by chrisgrieser** [comment]
There already is one: Using `aconf`, you can select `Run Annotation Extraction`. It will filter your PDFs, sorting the most recently modified ones on top. 🙂

**Comment by chrisgrieser** [comment]
Also, almost forgot: there is also the keyword `anno` which you can use to search for PDFs. It does exactly what you want, too. 

(I only forgot to document it, updated the readme, thanks!)
