### ISSUE TITLE
Feature Request: Modify the file name requirement of citekey_[...].pdf to just citekey.pdf

### ISSUE THREAD

**Issue by SebastianBehrens** [chrisgrieser/pdf-annotation-extractor-alfred#7]
### Feature Requested

I wondered whether it would be possible to allow one to change the requirement for an underscore in the pdfs-title through some workflow addition, or manually somewhere in the workflow or its file.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have read the README and also checked that the `aconf` does not already offer an option for the feature I am requesting.

**Comment by chrisgrieser** [comment]
good idea – implemented in latest release
